name: build-master
on: [push]
jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle test
        run: gradle clean test
  
  build: 
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: gradle build
        run: gradle clean build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  artifact:
    name: publish - GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: gradle install
        run: gradle clean install --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
