name: build-master
on: [push]
jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle test
        run: gradle clean test
  
  build: 
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: build with gradle
        run: ./gradlew clean build
      
  publish:
    needs: build
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v5      
        with:
         image: kameshsuddala/ezreach
         tags: v1, latest
         registry: docker.io
         dockerfile: ./Dockerfile
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        

   
